version: '{build}'


branches:
  only:
    - master

platform:
  - x86

environment:
  matrix:
    - build: Qt5.11.0-mingw32
      name: win32
      platform: mingw
      qt: mingw53_32

init:
  - git config --global core.autocrlf input

build_script:
  - set PATH=C:\Qt\5.11.0\%qt%\;C:\Qt\5.11.0\%qt%\bin;C:\Qt\5.11.0\%qt%\%qt%\msys\1.0\bin;%PATH%
  - cd \projects\bitcurrency
  - qmake bitcurrency-qt.pro
  - mingw32-make
  - make
