sudo: true
language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libdb++-dev
            - libssl1.01-dev
            - libboost-all-dev
            - libminiupnpc-dev
            - libqrencode-dev
            - libsodium-dev
            - qt5-default
            - qt5-qmake
            - qtbase5-dev-tools
            - qttools5-dev-tools
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 "


before_install:
    - eval "${MATRIX_EVAL}"
