sudo: true
language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      dist: xenial
      env: ARCH=i686
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - build-essential
            - libdb++-dev
            - libssl-dev
            - libboost-all-dev
            - libminiupnpc-dev
            - libqrencode-dev
            - libsodium-dev
            - qt5-default
            - qt5-qmake
            - qtbase5-dev-tools
            - qttools5-dev-tools

      script:
        - pushd src
        - make -f makefile.unix
        - popd
        - qmake && make
        - ./share/build-deb.sh `pwd`/contrib/debian `pwd`/ "X86"
        - ls -l

    # works on Precise and Trusty
    - os: linux
      dist: xenial
      env: ARCH=x86_64
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - build-essential
            - libdb++-dev
            - libssl-dev
            - libboost-all-dev
            - libminiupnpc-dev
            - libqrencode-dev
            - libsodium-dev
            - qt5-default
            - qt5-qmake
            - qtbase5-dev-tools
            - qttools5-dev-tools

      script:
        - pushd src
        - make -f makefile.unix
        - popd
        - qmake && make
        - ./share/build-deb.sh `pwd`/contrib/debian `pwd`/ "X86_64"
        - ls -l
